#include "TableCheck.h"
#define Nk 4
#define Nb 4
#define Nr 10
//expands key into subkeys
class KeyExpand
{
 public:
  KeyExpand(char *k, char *tf,char q);
  void run();
  static void rotWord(unsigned char *a);//rotates a 4 byte array left by one

  unsigned char w[Nb*(Nr+1)][4];//the subkeys generated by this class
 private:
  unsigned char key[16];//the inputted key converted into hex values
  unsigned char s[256];//s table from the tablefile
  char quiet;//when this class is being used by encrypt/decrypt, it doesnt make any output

  void printRound(int i);//prints output for a round
  void subWord(unsigned char *a);//performs substitution on the 4 byte array passed to it
  
  void xorWord(unsigned char *a, unsigned char *b,unsigned char *r);//xors 2 4 byte arrays and puts result in r
  void getR(unsigned char *r, int i);//calculates r word for the i value
  void printWord(unsigned char *a);//prints a 4 byte array
};
